deployment:
  tasks:
    - export REPOPATH=/home/tiseby/zbuduem.by/repository/frontend/*
    - export SITEPATH=/home/tiseby/zbuduem.by/frontend/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
